### ISSUE TITLE
Webhooks wont trigger any more

### ISSUE THREAD

**Issue by ScarLp** [tobimori/streamdeck-ifttt#10]
Idk why but the plugin stopped working entirely at first everything worked like a charm for a few weeks now nothing works anymore webhooks dont work anymore at all i tried reinstalling didnt fix it either :/ 

Cheers

**Comment by tobimori** [comment]
Make sure you're using the latest Stream Deck update as the latest major release had an regression that broke this plugin.

**Comment by ScarLp** [comment]
sadly this didnt work :(

**Comment by tobimori** [comment]
Then this is unlikely to be caused by this plugin but rather an error with your setup. Make sure your data is correct and try triggering the webhook url manually.

**Comment by ScarLp** [comment]
i finally fixed it damn it had luckily nothing to do with your plugin idk why but the webhook application kinda messed no webhooks would trigger at all i reseted my webhook key and put in the new one now everything works again :)
