### ISSUE TITLE
Webhook triggers only on every third press

### ISSUE THREAD

**Issue by Jaykulina** [tobimori/streamdeck-ifttt#11]
I'm triggering a smart outlet via webhook and somehow tghe function only triggers on every third button press. At first i thought it might be a problem with the toggle switch but i also tried it as two single actions. (one for on and one for off) And i get the same result.
Tried it with a different outlet as well. Still the same. Would be great if you can help me out here.

**Comment by tobimori** [comment]
This seems to be an issue on the integration of IFTTT and your smart outlet. The plugin simply just sends a web request to the IFTTT server, not different from opening a website in your browser.

Can you try accessing the webhook URL with your browser and see if it on triggers every third time there too?
