### ISSUE TITLE
How to add an existing applet?

### ISSUE THREAD

**Issue by Tenevyk** [tobimori/streamdeck-ifttt#4]
Hey!
Thank you for your plugin to Elgato Stream Deck!
I wonder how I could link an applet that I've already created.
Because through the plugin I can create a new only.
Could you, please, add the required functionality to your plugin?
That would be awesome!
Thank you.

**Comment by tobimori** [comment]
Hi,
this is not possible, because IFTTT only allows one trigger per applet.

**Comment by Tenevyk** [comment]
Okay, thank you.
