### ISSUE TITLE
Does this code work with integrated Maker?

### ISSUE THREAD

**Issue by Tenevyk** [tobimori/streamdeck-ifttt#5]
I'm sorry for bothering you, @tobimori , but I just tried lots of times to make your plugin works and failed.
When I've started to search for a maker key, I found that Maker was completely integrated in IFTTT.
Alas, their documentation is quite unclear and I failed to found any information to understand how calls that maker key now.
So, I've tried all the keys which I found and got no positive result.
When I saw when you updated this plugin last time, I understood that it may contain old API.
Could you, please, update the code?
Would be very grateful for your reply.

**Comment by tobimori** [comment]
The plugin is working fine, no update needed if you use the correct branch or the version available in the Elgato Stream Deck Store.
This plugin is made for using the "Maker" integration. (or Webhooks, Maker Webhooks, whatever)
Login to IFTTT, then click on the Create new Applet button in the property inspector of a Stream Deck button and create your actions.
After you linked the service for webhooks to your IFTTT account, the maker key can be found [here](https://ifttt.com/maker_webhooks) if you click on "Documentation".

**Comment by Tenevyk** [comment]
Thank you, @tobimori !

**Comment by Tenevyk** [comment]
Sorry, one more question. Where I should take an event name? From the address bar?

**Comment by tobimori** [comment]
The event name is what you enter in the text box when creating a new applet with a webhooks trigger on IFTTT

**Comment by Tenevyk** [comment]
> The event name is what you enter in the text box when creating a new applet with a webhooks trigger on IFTTT
Thank you

**Comment by Tenevyk** [comment]
> 
> 
> > The event name is what you enter in the text box when creating a new applet with a webhooks trigger on IFTTT
Thank you
