### ISSUE TITLE
Non-global maker key setting

### ISSUE THREAD

**Issue by markusem** [tobimori/streamdeck-ifttt#6]
Hello @tobimori , thanks for sharing your plugin to the Elgato Stream Deck!
I was wondering if it was possible to have a setting that no longer makes the maker key global?  I know that in previous versions that was the case (i am able to use v1.3 temporarily for my needs, but I need to uninstrall 2.0 and reinstall 1.3 again after every reboot), but would like to implement something that requires different maker keys which doesn't work in the plugin in its current iteration.
If this is not possible (or a pain in the behind!) I understand, but I am hoping it is doable!
My thanks in advance.

**Comment by tobimori** [comment]
Hi,
this is a very unspecific feature I probably won't add.

As a workaround for the auto updater, you can download v1.3 and change the version number in the json file from 1.3 to something above 2.0. 
You can find the IFTTT plugin either in `~/Library/Application Support/com.elgato.StreamDeck/Plugins/` (macOS) or `%appdata%\Elgato\StreamDeck\Plugins` (Windows).
Be aware, that v1.3 still depends on an older version of the Stream Deck SDK that might be removed in new versions.

**Comment by markusem** [comment]
Hi,
thanks for your help, advice and the warning!  This will work great for now and I appreciate you looking into it.
