### ISSUE TITLE
No trigger of Webhooks 

### ISSUE THREAD

**Issue by soundiesam** [tobimori/streamdeck-ifttt#7]
I have a webhook setup that triggers a switchbot to turn on my coffee machine. For some reason after works for a while the button on my streamdeck has stopped talking to webhook and webhook isn't triggering the switchbot. Nothing has changed. I reset this up last week as it stopped working last week and it was working again.

**Comment by arces** [comment]
I had something simular happen. Only thing I can think of is that I upgraded from Windows 10 -> 11.  I was getting the Yellow Triangle with the ! in the middle. I uninstalled, reinstalled, and put my key back there in one of the buttons, and all of them work now.... Strange
